<script>
import PostPreview from '../components/PostPreview.vue'

export default {
  data() {
    return {
      'posts': Object,
      'category': String,
    }
  },
  components: {
    PostPreview
  },
  computed: {
      haserror() {
        console.log('this.error: ' + this.error)
        return this.error ? true : false;
    }
  },
  mounted() {
    this.getposts();
  },
  methods: {
    getposts() {
      var self = this
        this.axios.get('/api/posts/')
        .then(response => {
          const rd = response.data;
          this.posts = rd.posts;
          this.error = response.data.error
        })
        .catch(function (error) {
          self.error = error;
        })
        .then(function () {
          // always executed
      });  
    }
  }
}
</script>

<!-- need to implement
  properly designed with carousel view etc. Should look good in any screen size
  !-->
<template>
  <div class="container">
  <div v-if="haserror" class="alert alert-danger" role="alert">
    <p>{{ error }}</p>
  </div>
    <!-- generated by for loop from response from db -->
    <div class="row">
      <div v-for="post in posts" :key="post" class="col-sm px-4">
        <PostPreview :title="post.title" :price="post.price" :postID="post._id" :imgs="post.imgs" />
      </div>
    </div>
</div>
</template>

