<script>
export default {
  //these are public variables that parents can v-bind to
  props: {
      'posts': Object,
  }
}
</script>

<!-- need to implement
  properly designed with carousel view etc. Should look good in any screen size
  !-->
<template>
  <div class="container">
    <!-- generated by for loop from response from db -->
    <PostPreview />
</div>
</template>

