<script>
import PostPreview from '../components/PostPreview.vue'
import axios from 'axios'

export default {
  data() {
    return {
      'posts': Object,
    }
  },
  components: {
    PostPreview
  },
  mounted() {
    this.tryAjax();
  },
  methods: {
    tryAjax() {
      const id = (this.$route.params.category ? this.$route.params.category : "");
        axios.get('http://localhost:3001/api/category/' + id)
        .then(response => {
          const rd = response.data;
          console.log(rd)
          this.posts = rd.documents
          this.error = response.data.error
          this.ogdata = false
        })
        .catch(function (error) {
          this.error = error;
        })
        .then(function () {
          // always executed
      });  
    }
  }
}
</script>

<!-- need to implement
  properly designed with carousel view etc. Should look good in any screen size
  !-->
<template>
  <div class="container">
    <!-- generated by for loop from response from db -->
    <div class="grid">
      <div v-for="post in posts" :key="post">
        <PostPreview :title="post.title" :price="post.price" :postID="post._id" />
      </div>
    </div>
</div>
</template>

