<script>
import PostPreview from '../components/PostPreview.vue'
import { useUser } from '@/stores/user'

export default {
  data() {
    return {
      posts: Object,
      error: String
    }
  },
  setup() {
    const userStore = useUser()
    return {
      userStore,
    }
  },
  components: {
    PostPreview
  },
  computed: {
      haserror() {
        console.log('this.error: ' + this.error)
        return this.error ? true : false;
    }
  },
  mounted() {
    this.tryAjax();
  },
  methods: {
    tryAjax() {
      var self = this
        this.axios.get('http://localhost:3001/api/posts/user/' + this.userStore.user.user)
        .then(response => {
          const rd = response.data;
          this.posts = rd.posts;
          this.error = response.data.error
        })
        .catch(function (error) {
          self.error = error;
        })
        .then(function () {
          // always executed
      }); 
    }
  }
}
</script>

<!-- need to implement
  properly designed with carousel view etc. Should look good in any screen size
  !-->
<template>
  <div class="container">
    <!-- generated by for loop from response from db -->
    <div class="row">
      <div v-for="post in posts" :key="post" class="col-sm px-4">
        <PostPreview :title="post.title" :price="post.price" :postID="post._id" :imgs="post.imgs" />
      </div>
    </div>
</div>
</template>

